#include "balance_control.hpp"
#include "task3_motion_control.hpp"
#include "task3_sequence.hpp"

#include <cassert>
#include <cmath>
#include <cstdio>

using namespace ball_stepper;

namespace {

void testSequence()
{
    AppConfig config;
    config.pipeLengthCm = 10.0;
    config.task3OffsetCm = 5.0;
    config.task3NegativeTargetBiasCm = 0.0;
    config.task3PositiveToleranceCm = 0.20;
    config.task3ArrivalConfirmFrames = 2;
    config.task3FinalToleranceCm = 0.20;
    config.task3FinalRightToleranceCm = 0.02;
    config.task3FinalSpeedCmS = 0.6;
    config.task3FinalStableMs = 250;

    Task3Sequence sequence(config);
    sequence.start(0.0);

    // A detection gap cannot be combined with the next measurement to fake a
    // +5 arrival.  The phase changes only inside the 0.20 cm target window.
    sequence.update(9.80, 2.0, 0.01);
    sequence.onMeasurementLost();
    sequence.update(9.80, 2.0, 0.04);
    assert(sequence.phase() == Task3Phase::MoveToPositive);
    sequence.update(9.85, 2.0, 0.05);
    assert(sequence.phase() == Task3Phase::MoveToNegative);
    assert(std::abs(sequence.targetCm()) < 1e-9);

    // Low speed at the right side of -5 is still not completion.
    sequence.update(0.30, 0.0, 0.10);
    sequence.update(0.30, 0.0, 0.20);
    assert(sequence.phase() == Task3Phase::MoveToNegative);

    sequence.update(0.01, 0.0, 0.30);
    sequence.update(0.01, 0.0, 0.56);
    assert(sequence.phase() == Task3Phase::HoldNegative);
}

AppConfig makePdiConfig()
{
    AppConfig config;
    config.task3MoveRightPositionKpDegPerCm = 0.350;
    config.task3MoveLeftPositionKpDegPerCm = 0.080;
    config.task3VelocityKdDegPerCmS = 0.040;
    config.task3IntegralKiDegPerCmSecond = 0.400;
    config.task3IntegralZoneCm = 3.00;
    config.task3IntegralSpeedLimitCmS = 0.8;
    config.task3IntegralLimitCmSeconds = 1.00;
    config.task3BreakawayErrorCm = 0.35;
    config.task3BreakawaySpeedCmS = 0.35;
    config.task3BreakawayDelaySeconds = 0.08;
    config.task3BreakawayRampDegPerSecond = 0.80;
    config.task3MoveRightBreakawayMaximumAngleDeg = 0.11;
    config.task3MoveLeftBreakawayMaximumAngleDeg = 0.28;
    config.task3MoveRightOutputAngleLimitDeg = 0.80;
    config.task3MoveLeftOutputAngleLimitDeg = 0.60;
    return config;
}

void testPdiMotionController()
{
    const AppConfig config = makePdiConfig();
    Task3MotionController controller(config);

    // Initial O -> O+5 value is generated by P, not a fixed angle.
    const Task3MotionCommand positiveStart = controller.update(
        Task3Phase::MoveToPositive, -5.0, 0.0, 0.01);
    assert(positiveStart.mode == Task3MotionMode::TrackingPd);
    assert(std::abs(positiveStart.proportionalAngleDeg + 1.75) < 1e-9);
    assert(std::abs(positiveStart.angleDeg + 0.80) < 1e-9);
    assert(std::abs(positiveStart.baseOutputLimitDeg - 0.80) < 1e-9);

    // At the same position error, greater rightward speed increases a positive
    // D term and reduces the rightward drive before the ball reaches +5.
    const Task3MotionCommand positiveFast = controller.update(
        Task3Phase::MoveToPositive, -1.5, 5.0, 0.01);
    assert(std::abs(positiveFast.proportionalAngleDeg + 0.525) < 1e-9);
    assert(std::abs(positiveFast.derivativeAngleDeg - 0.20) < 1e-9);
    assert(std::abs(positiveFast.angleDeg + 0.325) < 1e-9);

    // Equal position-error magnitudes intentionally produce different P terms
    // because the measured mechanism requires more authority to move right.
    Task3MotionController rightController(config);
    Task3MotionController leftController(config);
    const Task3MotionCommand equalErrorRight = rightController.update(
        Task3Phase::MoveToPositive, -2.0, 0.0, 0.01);
    const Task3MotionCommand equalErrorLeft = leftController.update(
        Task3Phase::MoveToNegative, 2.0, 0.0, 0.01);
    assert(std::abs(equalErrorRight.proportionalAngleDeg + 0.70) < 1e-9);
    assert(std::abs(equalErrorLeft.proportionalAngleDeg - 0.16) < 1e-9);
    assert(std::abs(equalErrorRight.angleDeg) >
           3.0 * std::abs(equalErrorLeft.angleDeg));

    // The 10 cm return target step stays below the independent +0.40 deg limit.
    const Task3MotionCommand returnStart = controller.update(
        Task3Phase::MoveToNegative, 10.0, 0.0, 0.01);
    assert(std::abs(returnStart.angleDeg - 0.60) < 1e-9);
    assert(std::abs(returnStart.baseOutputLimitDeg - 0.60) < 1e-9);

    // When the ball is moving left faster, D becomes more negative and turns
    // the pipe toward braking without a separate braking mode or fixed angle.
    const Task3MotionCommand returnSlow = controller.update(
        Task3Phase::MoveToNegative, 1.0, -2.0, 0.01);
    const Task3MotionCommand returnFast = controller.update(
        Task3Phase::MoveToNegative, 1.0, -5.0, 0.01);
    assert(std::abs(returnSlow.derivativeAngleDeg + 0.08) < 1e-9);
    assert(std::abs(returnFast.derivativeAngleDeg + 0.20) < 1e-9);
    assert(returnFast.angleDeg < returnSlow.angleDeg);
    assert(returnFast.angleDeg < 0.0);

    // I appears near either target at low speed and remains much smaller than
    // the travel envelope.  It is cleared on every target reversal.
    Task3MotionController positiveIntegralController(config);
    Task3MotionCommand positiveFinalCommand;
    for (int index = 0; index < 10; ++index) {
        positiveFinalCommand = positiveIntegralController.update(
            Task3Phase::MoveToPositive, -0.25, 0.0, 0.10);
    }
    assert(positiveFinalCommand.integralWindowActive);
    assert(positiveFinalCommand.integralAngleDeg < 0.0);

    Task3MotionCommand finalCommand;
    for (int index = 0; index < 10; ++index) {
        finalCommand = controller.update(
            Task3Phase::HoldNegative, 0.25, 0.0, 0.10);
    }
    assert(finalCommand.mode == Task3MotionMode::HoldPdi);
    assert(finalCommand.integralWindowActive);
    assert(finalCommand.integralAngleDeg > 0.0);
    assert(finalCommand.integralAngleDeg < 0.41 + 1e-9);
    assert(finalCommand.angleDeg > finalCommand.proportionalAngleDeg);

    const Task3MotionCommand outsideIntegralWindow = controller.update(
        Task3Phase::HoldNegative, 3.10, 0.0, 0.01);
    assert(!outsideIntegralWindow.integralWindowActive);
    assert(std::abs(outsideIntegralWindow.integralAngleDeg) < 1e-12);

    Task3MotionController residualIntegralController(config);
    Task3MotionCommand residualCommand;
    for (int index = 0; index < 20; ++index) {
        residualCommand = residualIntegralController.update(
            Task3Phase::MoveToNegative, 1.9, 0.0, 0.10);
    }
    assert(residualCommand.integralWindowActive);
    assert(residualCommand.integralAngleDeg > 0.39);
    assert(residualCommand.integralAngleDeg <= 0.40 + 1e-9);

    // A large error with no measured ball response gradually expands the
    // output beyond the normal PD limit.  It is feedback-triggered and decays
    // immediately after the ball starts moving.
    Task3MotionController breakawayController(config);
    Task3MotionCommand stuckCommand;
    for (int index = 0; index < 30; ++index) {
        stuckCommand = breakawayController.update(
            Task3Phase::MoveToPositive, -5.0, 0.0, 0.02);
    }
    assert(stuckCommand.breakawayActive);
    assert(stuckCommand.breakawayAngleDeg < -0.10);
    assert(stuckCommand.angleDeg <
           -config.task3MoveRightOutputAngleLimitDeg);
    assert(stuckCommand.angleDeg >= -0.91 - 1e-9);

    Task3MotionCommand movingCommand;
    for (int index = 0; index < 6; ++index) {
        movingCommand = breakawayController.update(
            Task3Phase::MoveToPositive, -5.0, 2.0, 0.02);
    }
    assert(!movingCommand.breakawayActive);
    assert(std::abs(movingCommand.breakawayAngleDeg) < 1e-9);

    // Positive-angle breakaway has its own smaller authority and clamp.
    Task3MotionController leftBreakawayController(config);
    Task3MotionCommand leftStuckCommand;
    for (int index = 0; index < 30; ++index) {
        leftStuckCommand = leftBreakawayController.update(
            Task3Phase::MoveToNegative, 20.0, 0.0, 0.02);
    }
    assert(leftStuckCommand.breakawayActive);
    assert(std::abs(leftStuckCommand.breakawayAngleDeg - 0.28) < 1e-9);
    assert(std::abs(leftStuckCommand.angleDeg - 0.88) < 1e-9);

    // Hold must still overcome linkage play if the ball drifts well outside
    // the final I window after the sequence has reported completion.
    Task3MotionController holdBreakawayController(config);
    Task3MotionCommand holdStuckCommand;
    for (int index = 0; index < 30; ++index) {
        holdStuckCommand = holdBreakawayController.update(
            Task3Phase::HoldNegative, 2.5, 0.0, 0.02);
    }
    assert(holdStuckCommand.breakawayActive);
    assert(std::abs(holdStuckCommand.breakawayAngleDeg - 0.28) < 1e-9);
    assert(holdStuckCommand.angleDeg >
           holdStuckCommand.proportionalAngleDeg);
}

void testTwoFrameSpeedEstimator()
{
    BallStateEstimator estimator(0.005, 2);
    estimator.update(0.00, 0.00);
    estimator.update(0.10, 0.01);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS()) < 1e-12);

    // Current frame minus frame n-2: (0.40 - 0.00) / 0.02 = 20 cm/s.
    estimator.update(0.40, 0.02);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS() - 20.0) < 1e-9);
    assert(estimator.speedCmS() > 0.0);

    estimator.onMeasurementLost();
    estimator.update(0.50, 0.03);
    estimator.update(0.60, 0.04);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS()) < 1e-12);
}

} // namespace

int main()
{
    testSequence();
    testPdiMotionController();
    testTwoFrameSpeedEstimator();
    std::puts("task3 PDI and two-frame speed tests passed");
    return 0;
}
