#include "balance_control.hpp"
#include "task3_motion_control.hpp"
#include "task3_sequence.hpp"

#include <cassert>
#include <cmath>
#include <cstdio>

using namespace ball_stepper;

namespace {

void testSequence()
{
    AppConfig config;
    config.pipeLengthCm = 10.0;
    config.task3OffsetCm = 5.0;
    config.task3NegativeTargetBiasCm = 0.0;
    config.task3PositiveToleranceCm = 0.20;
    config.task3ArrivalConfirmFrames = 2;
    config.task3FinalToleranceCm = 0.20;
    config.task3FinalRightToleranceCm = 0.02;
    config.task3FinalSpeedCmS = 1.5;
    config.task3FinalStableMs = 80;

    Task3Sequence sequence(config);
    sequence.start(0.0);

    // A detection gap cannot be combined with the next measurement to fake a
    // +5 arrival.  The phase changes only inside the 0.20 cm target window.
    sequence.update(9.80, 2.0, 0.01);
    sequence.onMeasurementLost();
    sequence.update(9.80, 2.0, 0.04);
    assert(sequence.phase() == Task3Phase::MoveToPositive);
    sequence.update(9.85, 2.0, 0.05);
    assert(sequence.phase() == Task3Phase::MoveToNegative);
    assert(std::abs(sequence.targetCm()) < 1e-9);

    // Low speed at the right side of -5 is still not completion.
    sequence.update(0.30, 0.0, 0.10);
    sequence.update(0.30, 0.0, 0.20);
    assert(sequence.phase() == Task3Phase::MoveToNegative);

    sequence.update(0.01, 0.0, 0.30);
    sequence.update(0.01, 0.0, 0.39);
    assert(sequence.phase() == Task3Phase::HoldNegative);
}

AppConfig makePdiConfig()
{
    AppConfig config;
    config.task3PositionKpDegPerCm = 0.070;
    config.task3VelocityKdDegPerCmS = 0.020;
    config.task3IntegralKiDegPerCmSecond = 0.120;
    config.task3IntegralZoneCm = 0.50;
    config.task3IntegralSpeedLimitCmS = 1.0;
    config.task3IntegralLimitCmSeconds = 0.75;
    config.task3OutputAngleLimitDeg = 0.35;
    return config;
}

void testPdiMotionController()
{
    const AppConfig config = makePdiConfig();
    Task3MotionController controller(config);

    // Initial O -> O+5 value is generated by P, not a fixed angle.
    const Task3MotionCommand positiveStart = controller.update(
        Task3Phase::MoveToPositive, -5.0, 0.0, 0.01);
    assert(positiveStart.mode == Task3MotionMode::TrackingPd);
    assert(std::abs(positiveStart.proportionalAngleDeg + 0.35) < 1e-9);
    assert(std::abs(positiveStart.angleDeg + 0.35) < 1e-9);

    // At the same position error, greater rightward speed increases a positive
    // D term and reduces the rightward drive before the ball reaches +5.
    const Task3MotionCommand positiveFast = controller.update(
        Task3Phase::MoveToPositive, -3.0, 5.0, 0.01);
    assert(std::abs(positiveFast.proportionalAngleDeg + 0.21) < 1e-9);
    assert(std::abs(positiveFast.derivativeAngleDeg - 0.10) < 1e-9);
    assert(std::abs(positiveFast.angleDeg + 0.11) < 1e-9);

    // A 10 cm target step is bounded by the same 0.35 deg outer-loop limit.
    const Task3MotionCommand returnStart = controller.update(
        Task3Phase::MoveToNegative, 10.0, 0.0, 0.01);
    assert(std::abs(returnStart.angleDeg - 0.35) < 1e-9);

    // When the ball is moving left faster, D becomes more negative and turns
    // the pipe toward braking without a separate braking mode or fixed angle.
    const Task3MotionCommand returnSlow = controller.update(
        Task3Phase::MoveToNegative, 1.0, -2.0, 0.01);
    const Task3MotionCommand returnFast = controller.update(
        Task3Phase::MoveToNegative, 1.0, -5.0, 0.01);
    assert(std::abs(returnSlow.derivativeAngleDeg + 0.04) < 1e-9);
    assert(std::abs(returnFast.derivativeAngleDeg + 0.10) < 1e-9);
    assert(returnFast.angleDeg < returnSlow.angleDeg);
    assert(returnFast.angleDeg < 0.0);

    // I appears only near the final -5 target at low speed and remains much
    // smaller than the 0.35 deg travel envelope.
    Task3MotionCommand finalCommand;
    for (int index = 0; index < 10; ++index) {
        finalCommand = controller.update(
            Task3Phase::HoldNegative, 0.25, 0.0, 0.10);
    }
    assert(finalCommand.mode == Task3MotionMode::HoldPdi);
    assert(finalCommand.integralWindowActive);
    assert(finalCommand.integralAngleDeg > 0.0);
    assert(finalCommand.integralAngleDeg < 0.09 + 1e-9);
    assert(finalCommand.angleDeg > finalCommand.proportionalAngleDeg);

    const Task3MotionCommand outsideIntegralWindow = controller.update(
        Task3Phase::HoldNegative, 0.60, 0.0, 0.01);
    assert(!outsideIntegralWindow.integralWindowActive);
    assert(std::abs(outsideIntegralWindow.integralAngleDeg) < 1e-12);
}

void testTwoFrameSpeedEstimator()
{
    BallStateEstimator estimator(0.005, 2);
    estimator.update(0.00, 0.00);
    estimator.update(0.10, 0.01);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS()) < 1e-12);

    // Current frame minus frame n-2: (0.40 - 0.00) / 0.02 = 20 cm/s.
    estimator.update(0.40, 0.02);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS() - 20.0) < 1e-9);
    assert(estimator.speedCmS() > 0.0);

    estimator.onMeasurementLost();
    estimator.update(0.50, 0.03);
    estimator.update(0.60, 0.04);
    assert(std::abs(estimator.rawTwoFrameSpeedCmS()) < 1e-12);
}

} // namespace

int main()
{
    testSequence();
    testPdiMotionController();
    testTwoFrameSpeedEstimator();
    std::puts("task3 PDI and two-frame speed tests passed");
    return 0;
}
